language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - hhvm
  - nightly

install: composer install

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

script:
  - ./vendor/bin/phpcs --standard=phpcs.xml src/
  - ./vendor/bin/phpmd src/ text phpmd.xml
  - ./bin/runtests.sh
